# Generated by Django 4.0.5 on 2022-07-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Muebleria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del proveedor')),
                ('empresa', models.CharField(max_length=20, verbose_name='Empresa')),
                ('productoprov', models.CharField(max_length=50, verbose_name='Proveedor de...')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion de la sucursal')),
                ('empleados', models.TextField(null=True, verbose_name='Id de los empleados')),
            ],
        ),
    ]
